#!/usr/bin/env bash
# Compiles all three stages and demonstrates that the output of stage1 and stage2 ilc are the same given the ilc source code
set -euo pipefail

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

compile_ilc () {
  local prev_ilc="$1"
  local out_bin="$2"

  local asm="$tmpdir/${out_bin}.s"
  local obj="$tmpdir/${out_bin}.o"

  "$prev_ilc" < ilc.il > "$asm"
  nasm -f elf64 -o "$obj" "$asm"
  gcc -no-pie -z noexecstack -o "$out_bin" "$obj"
}

# Compile the Rust stage0 ilc
cargo build --release

# Compile stage1 ilc using Rust's stage0
cargo run --release -- ilc.il ilc_stage1

# Compile stage2 ilc using stage1 ilc
compile_ilc ./ilc_stage1 ./ilc_stage2

# Compare the assembly generated by stage1 and stage2
diff <(./ilc_stage1 < ilc.il) <(./ilc_stage2 < ilc.il)

echo "Done!"
